import { Inter } from "@next/font/google";
import Head from "next/head";
import About from "src/components/Organisms/About";
import Footer from "src/components/Organisms/Footer";
import Hero from "src/components/Organisms/Hero";
import Portfolio from "src/components/Organisms/Portfolio";
import Skills from "src/components/Organisms/Skills";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <About />
        <Skills />
        <Portfolio />
        <Footer />
      </main>
    </>
  );
}
